### ISSUE TITLE
update Jekyll and/or change blog posting to not require Jekyll

### ISSUE THREAD

**Issue by PJHouser** [OR-URISA-YPs/or-urisa-yps.github.com#17]
We're going to update Jekyll and/or simplify the repo for future contributors, perhaps without Jekyll. (Also, I am having trouble installing Jekyll; perhaps we should remove Jekyll for future blog posts in case future contributors have problems too?)

> The page build failed with the following error:
> 
> The submodule `_theme_packages/the-minimum` was not properly initialized with a `.gitmodules` file. For more information, see https://help.github.com/articles/page-build-failed-missing-submodule.
> 
> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:
> 
>   https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by PJHouser** [comment]
Or something! @ungoldman will help us so @alexatodd and I don't Godzilla all over.

**Comment by ungoldman** [comment]
#19 should resolve the build issues you were seeing. I added some instructions for creating a new blog post directly through github to the readme too.

**Comment by ungoldman** [comment]
Hey I think we solved this, can you close the issue?

**Comment by ungoldman** [comment]
Thanks @alexatodd!

**Comment by alexatodd** [comment]
@ungoldman thanks for pointing this out! ;-)
